SERVICE_ROLE_QUERIES = {

    # =========================================================
    # ELECTRICAL
    # =========================================================
    "Electrical": [
        "electrician",
        "need electrician",
        "urgent electrician",
        "please send electrician today",
        "can someone fix my fan",
        "fan not working since morning",
        "ceiling fan is moving very slow",
        "fan making loud noise at night",
        "fan stopped suddenly please help",
        "room fan only runs on full speed",
        "light not working in bedroom",
        "tube light keeps blinking",
        "bulb fused in kitchen",
        "switch board issue in hall",
        "socket is loose and sparking",
        "plug point not working",
        "power gone in one room only",
        "mcb keeps tripping",
        "short circuit smell coming",
        "wire is burning near switch",
        "voltage fluctuation damaging appliances",
        "electric meter box making sound",
        "inverter wiring problem",
        "geyser switch got burnt",
        "washing machine socket dead",
        "doorbell not ringing",
        "need new fan installation",
        "install led lights in balcony",
        "replace broken switch board",
        "move electric socket to other wall",
        "electrition needed urgently",
        "electrcian pls come fast",
        "fan nt working bro",
        "power off in my flat help",
        "switch se smoke aa raha hai",
        "bijli ka problem hai ghar me",
        "pankha nahi chal raha",
        "light chali gayi sirf bedroom me",
        "switch board jal gaya",
        "wire se spark aa raha hai",
        "mcb baar baar trip ho raha",
        "current lag raha socket se",
        "bijli wala bhejo jaldi",
        "ghar ki wiring check karni hai",
        "పంకా పని చేయడం లేదు",
        "లైట్ ఆన్ కావడం లేదు",
        "స్విచ్ బోర్డు కాలిపోయింది",
        "వైర్ నుంచి స్పార్క్ వస్తోంది",
        "ఇంట్లో కరెంట్ సమస్య ఉంది",
        "ఫ్యాన్ చాలా స్లోగా తిరుగుతోంది",
        "ఎలక్ట్రిషియన్ వెంటనే కావాలి",
        "fan repair need urgent my kid scared",
        "please help there is burning smell from wire",
        "half house no electricity what to do",
        "my mother is alone and lights are gone",
        "electric man come fast pls",
        "fan fix kar do yaar garmi bahut hai",
        "lite not on after switch",
        "soket broken charger not working",
        "mcb triping again again",
        "need wiring person for new room",
        "can u send bijli worker now",
        "there is spark when I plug charger",
        "main switch is not turning on",
    ],

    # =========================================================
    # PLUMBING
    # =========================================================
    "Plumbing": [
        "plumber",
        "need plumber",
        "urgent plumber",
        "please send plumber now",
        "pipe leak in bathroom",
        "water leakage from ceiling",
        "tap is leaking continuously",
        "kitchen sink blocked",
        "bathroom drain clogged",
        "toilet flush not working",
        "water pipe burst outside",
        "wash basin pipe leaking",
        "shower has no water pressure",
        "geyser pipe leaking",
        "water tank overflowing",
        "commode is overflowing",
        "sink water coming back",
        "bathroom floor full of water",
        "main water line issue",
        "tap handle broken",
        "install new kitchen tap",
        "replace bathroom faucet",
        "fix western toilet seat",
        "drain smell coming badly",
        "pipe under sink broken",
        "water motor pipe connection issue",
        "plumbr needed fast",
        "plummer come urgent",
        "pipe leakng badly",
        "bathrom full water",
        "tap drip drip all night",
        "flush not stoping",
        "water coming no in bathroom",
        "pani leak ho raha hai",
        "nal kharab hai",
        "pipe phat gaya jaldi bhejo",
        "bathroom me pani bhar gaya",
        "flush kaam nahi kar raha",
        "sink block ho gaya",
        "drain me badbu aa rahi hai",
        "tank overflow ho raha",
        "plumber bhai urgent chahiye",
        "kitchen pipe se pani tapak raha",
        "నల్లా నుంచి నీరు కారుతోంది",
        "బాత్‌రూమ్ పైప్ లీక్ అవుతోంది",
        "ఫ్లష్ పని చేయడం లేదు",
        "సింక్ బ్లాక్ అయింది",
        "డ్రెయిన్ నీరు బయటికి వస్తోంది",
        "పైప్ పగిలిపోయింది వెంటనే రండి",
        "ప్లంబర్ కావాలి",
        "please help water is everywhere",
        "my bathroom is flooding badly",
        "children cannot use toilet flush broken",
        "tap broke and water not stopping",
        "send someone I am panicking water leak",
        "kitchen sink choked need help",
        "pani ruk nahi raha help",
        "need pipe guy at home",
        "washroom leakage fix karna hai",
        "leak under basin pls repair",
        "no water in taps since morning",
        "drain blocked bad smell unbearable",
        "bathroom pipe repair need today",
        "can plumber come in evening",
    ],

    # =========================================================
    # AC REPAIR
    # =========================================================
    "AC Repair": [
        "ac repair",
        "ac service",
        "ac technician",
        "need ac mechanic",
        "ac not cooling",
        "split ac issue",
        "window ac repair",
        "ac gas refill needed",
        "ac water leak inside room",
        "ac making loud noise",
        "ac remote not working",
        "ac compressor not starting",
        "ac fan running but no cooling",
        "air conditioner stopped suddenly",
        "room not getting cold",
        "ac airflow is weak",
        "ac smells bad when on",
        "ac filter cleaning needed",
        "ac installation for new flat",
        "ac uninstall and reinstall",
        "outdoor unit making sound",
        "ac trips mcb after starting",
        "cooling problem in bedroom ac",
        "annual ac maintenance needed",
        "water dripping from indoor ac",
        "ac service before summer",
        "ac coolng issue",
        "air condtion repair",
        "ac technican pls",
        "ac not turn on",
        "cooling no coming",
        "ac gas finish maybe",
        "ac ka cooling nahi hai",
        "ac pani leak kar raha",
        "ac kharab hai jaldi bhejo",
        "split ac service chahiye",
        "window ac awaaz kar raha hai",
        "ac remote kaam nahi kar raha",
        "room garam hai ac chal raha phir bhi",
        "ac me gas bharwani hai",
        "ac band ho gaya achanak",
        "ac wala bhejo please",
        "summer me ac repair urgent hai",
        "ఏసీ చల్లగా చేయడం లేదు",
        "ఏసీ నుంచి నీరు కారుతోంది",
        "ఏసీ సర్వీస్ కావాలి",
        "ఏసీ శబ్దం చేస్తోంది",
        "ఏసీ రిమోట్ పని చేయడం లేదు",
        "ఏసీ మెకానిక్ వెంటనే కావాలి",
        "స్ప్లిట్ ఏసీ ఇన్‌స్టాలేషన్ కావాలి",
        "please help baby cannot sleep ac not cooling",
        "I am sweating badly ac stopped",
        "need urgent ac fix tonight",
        "ac repair guy come fast please",
        "my parents room ac not working",
        "ac service kar do kal se smell aa rahi",
        "cooling kam hai gas check karo",
        "indoor ac leaking on bed",
        "ac start hota hai then off",
        "ac servicing need at home",
        "can u send ac person now",
        "air conditioner not cooling properly",
        "ac makes ice on pipe",
        "need ac installation after shifting",
    ],

    # =========================================================
    # CARPENTER
    # =========================================================
    "Carpenter": [
        "carpenter",
        "need carpenter",
        "wood work needed",
        "furniture repair",
        "door repair",
        "window frame repair",
        "table leg broken",
        "chair repair needed",
        "bed making noise",
        "cupboard door loose",
        "kitchen cabinet repair",
        "wooden shelf installation",
        "wardrobe hinge broken",
        "drawer not closing",
        "door lock fitting",
        "main door is jammed",
        "sliding door repair",
        "wooden cot broken",
        "study table assembly",
        "install curtain rods",
        "fix modular kitchen cabinet",
        "wood polish required",
        "replace door handle",
        "make small wall shelf",
        "sofa wooden frame cracked",
        "carpenter for furniture assembly",
        "carpnter needed",
        "furnture repair pls",
        "woodn door broken",
        "cupbord not closing",
        "chair leg brken",
        "bed noise too much",
        "wood ka kaam chahiye",
        "darwaza kharab hai",
        "furniture toot gaya",
        "almari ka hinge toot gaya",
        "bed char char awaaz karta hai",
        "table ka pair hil raha hai",
        "kitchen cabinet band nahi hota",
        "door lock lagwana hai",
        "parda rod fit karna hai",
        "carpenter bhai bhejo",
        "lakdi ka shelf banana hai",
        "కార్పెంటర్ కావాలి",
        "తలుపు సరిగా మూసుకోవడం లేదు",
        "కుర్చీ కాలు విరిగింది",
        "బెడ్ శబ్దం చేస్తోంది",
        "కప్పర్డ్ తలుపు లూజ్ అయింది",
        "చెక్క పని చేయించాలి",
        "డోర్ లాక్ ఫిట్ చేయాలి",
        "please help door is stuck and I cannot close it",
        "my cupboard broke and clothes are outside",
        "need carpenter urgently before guests come",
        "bed broken cannot sleep properly",
        "chair almost falling please fix",
        "door ka latch toot gaya help",
        "drawer stuck open need repair",
        "wood repair person required today",
        "can someone assemble my new bed",
        "need shelf fitting in kitchen",
        "main door hinge problem urgent",
        "carpenter for office table repair",
        "fix broken wooden window",
        "need custom plywood cutting",
    ],

    # =========================================================
    # CLEANING
    # =========================================================
    "Cleaning": [
        "cleaning service",
        "house cleaning",
        "home cleaning",
        "bathroom cleaning",
        "kitchen cleaning",
        "deep cleaning needed",
        "sofa cleaning",
        "carpet cleaning",
        "office cleaning",
        "floor cleaning",
        "water tank cleaning",
        "maid cleaning service",
        "post party cleaning",
        "move out cleaning",
        "balcony cleaning",
        "window cleaning service",
        "toilet deep clean",
        "kitchen grease cleaning",
        "dust cleaning after renovation",
        "mattress cleaning",
        "tiles cleaning bathroom",
        "stain removal from sofa",
        "weekly home cleaning",
        "clean whole flat today",
        "sanitize room after illness",
        "cleaning lady needed",
        "cleanng service pls",
        "cleanr needed urgent",
        "bathrom clean karna",
        "house very dirty help",
        "kichen messy cleaning",
        "need floor mop person",
        "ghar cleaning chahiye",
        "ghar saaf karna hai",
        "bathroom bahut ganda hai",
        "kitchen me tel chipak gaya",
        "sofa pe stain hai clean karo",
        "poora flat saaf karwana hai",
        "party ke baad cleaning chahiye",
        "maid bhejo kal subah",
        "paani tank clean karna hai",
        "office saaf karwana hai",
        "deep cleaning jaldi chahiye",
        "ఇల్లు శుభ్రం చేయాలి",
        "బాత్‌రూమ్ క్లీనింగ్ కావాలి",
        "కిచెన్ చాలా మురికిగా ఉంది",
        "సోఫా క్లీనింగ్ చేయాలి",
        "ఆఫీస్ క్లీనింగ్ కావాలి",
        "వాటర్ ట్యాంక్ శుభ్రం చేయాలి",
        "డీప్ క్లీనింగ్ వెంటనే కావాలి",
        "please help house is a mess",
        "guests coming and bathroom is dirty",
        "I feel embarrassed kitchen needs cleaning",
        "need cleaner urgently today",
        "my room smells bad please clean",
        "ghar bahut messy hai pls send cleaner",
        "cleaning needed after paint work",
        "need someone to scrub bathroom tiles",
        "can u send cleaner in morning",
        "sofa dirty due to kids need wash",
        "balcony has bird dirt clean it",
        "need maid for one time cleaning",
        "floor sticky after party",
        "clean my apartment before shifting",
    ],

    # =========================================================
    # PAINTING
    # =========================================================
    "Painting": [
        "painting service",
        "house painting",
        "wall painting",
        "paint work",
        "room painting",
        "interior painting",
        "exterior painting",
        "wall repaint needed",
        "home paint color change",
        "paint peeling from wall",
        "ceiling paint repair",
        "water stain on wall paint",
        "paint touch up required",
        "paint balcony grill",
        "door painting needed",
        "texture painting for living room",
        "primer and paint work",
        "one room repaint",
        "new flat painting",
        "office wall painting",
        "paint cracked near window",
        "wall putty and painting",
        "paint after seepage repair",
        "kids room color change",
        "painter for rental house",
        "whitewash home before moving",
        "paintng work pls",
        "painter urgent need",
        "wall panting required",
        "room color chnge",
        "paint peelng badly",
        "witewash needed",
        "ghar paint karna hai",
        "wall color change karna hai",
        "painter bhejo jaldi",
        "deewar ka paint nikal raha hai",
        "kamre ki painting chahiye",
        "ceiling pe daag hai paint karo",
        "ghar ka whitewash karwana hai",
        "balcony grill paint karni hai",
        "putty aur paint ka kaam hai",
        "rental flat paint karwana hai",
        "paint ka touch up chahiye",
        "పెయింటర్ కావాలి",
        "ఇంటి పెయింటింగ్ చేయాలి",
        "గోడ రంగు మార్చాలి",
        "గోడపై పెయింట్ ఊడిపోతోంది",
        "రూమ్ పెయింటింగ్ కావాలి",
        "సీలింగ్ మీద మచ్చలు ఉన్నాయి",
        "పెయింటింగ్ పని వెంటనే కావాలి",
        "please paint before my family arrives",
        "wall looks very bad need repaint",
        "landlord asking for paint touch up",
        "need urgent painter before festival",
        "paint smell old and wall dirty",
        "ghar ki deewar bahut kharab lag rahi",
        "one bedroom paint karwana hai",
        "can painter come Sunday",
        "need waterproof paint on damp wall",
        "paint patches after leakage repair",
        "office cabin repaint needed",
        "door polish and paint required",
        "need color suggestion and painting",
        "wall putty cracked need painter",
    ],

    # =========================================================
    # GARDENING
    # =========================================================
    "Gardening": [
        "gardener",
        "need gardener",
        "garden cleaning",
        "plant maintenance",
        "grass cutting",
        "lawn mowing",
        "tree trimming",
        "garden setup",
        "garden watering",
        "plant care service",
        "remove weeds from garden",
        "trim balcony plants",
        "terrace garden maintenance",
        "soil change for pots",
        "plant repotting service",
        "fertilizer for plants",
        "hedge trimming needed",
        "small lawn maintenance",
        "clean dry leaves in garden",
        "set up kitchen garden",
        "install balcony planters",
        "garden pest control needed",
        "rose plant pruning",
        "grass is too long",
        "plants are drying",
        "gardening help today",
        "gardning service",
        "gardner urgent",
        "grass cuting needed",
        "plant maintanance pls",
        "lawn clean krna",
        "garden messy hai",
        "maali chahiye",
        "bagicha saaf karna hai",
        "ghaas bahut badh gayi hai",
        "plants sukh rahe hain",
        "ped ki trimming chahiye",
        "balcony plants ka care karna hai",
        "mitti change karni hai pots me",
        "garden me ghaas kaatna hai",
        "maali jaldi bhejo",
        "terrace garden set karna hai",
        "paudhon me keede lag gaye",
        "తోట శుభ్రం చేయాలి",
        "మాలి కావాలి",
        "గడ్డి కత్తిరించాలి",
        "మొక్కలు ఎండిపోతున్నాయి",
        "చెట్టు కొమ్మలు ట్రిమ్ చేయాలి",
        "కుండీల్లో మట్టి మార్చాలి",
        "గార్డెనింగ్ సేవ కావాలి",
        "please save my plants they are dying",
        "garden looks terrible before guests come",
        "need gardener urgently this weekend",
        "my lawn is overgrown badly",
        "plants falling from balcony please fix",
        "maali bhejo plants mar rahe hain",
        "need monthly garden maintenance",
        "can someone water plants while I travel",
        "trim tree branches touching window",
        "remove weeds from front yard",
        "setup few indoor plants",
        "need help arranging pots",
        "garden cleaning after rain",
        "lawn mowing required tomorrow",
    ],

    # =========================================================
    # MASSAGE
    # =========================================================
    "Massage": [
        "massage service",
        "body massage",
        "spa massage",
        "home massage",
        "head massage",
        "foot massage",
        "full body massage",
        "massage therapist",
        "back pain massage",
        "neck pain massage",
        "shoulder pain massage",
        "stress relief massage",
        "deep tissue massage",
        "relaxing massage at home",
        "sports massage needed",
        "leg pain massage",
        "oil massage service",
        "massage for body ache",
        "therapist for muscle pain",
        "home spa appointment",
        "need female massage therapist",
        "need male massage therapist",
        "massage after long travel",
        "foot reflexology service",
        "head and shoulder massage",
        "book massage tonight",
        "massag needed",
        "masage therapist pls",
        "body pain relief massage",
        "backpain massage urgent",
        "foot masaj needed",
        "spa at home pls",
        "massage chahiye",
        "body pain hai massage chahiye",
        "sir dard hai head massage",
        "pair me dard hai foot massage",
        "back pain ke liye massage",
        "stress bahut hai relaxing massage",
        "ghar pe massage therapist bhejo",
        "full body massage karwana hai",
        "neck pain relief chahiye",
        "spa service ghar par chahiye",
        "massage wala kal bhejna",
        "మసాజ్ కావాలి",
        "బాడీ మసాజ్ కావాలి",
        "తలనొప్పి ఉంది హెడ్ మసాజ్ కావాలి",
        "కాళ్ల నొప్పికి ఫుట్ మసాజ్ కావాలి",
        "బ్యాక్ పెయిన్ మసాజ్ కావాలి",
        "ఇంట్లో మసాజ్ సేవ కావాలి",
        "రిలాక్సింగ్ మసాజ్ వెంటనే కావాలి",
        "please help my back is hurting badly",
        "I am exhausted need massage",
        "neck is stiff after work need therapist",
        "can someone come for foot massage",
        "body pain se so nahi pa raha",
        "stress zyada hai massage book karo",
        "need massage for my mother back pain",
        "home massage appointment in evening",
        "shoulder locked need massage therapy",
        "deep tissue massage near me",
        "need spa therapist at home",
        "leg cramps massage needed",
        "head massage urgent migraine feeling",
        "book relaxing body massage",
    ],
}


# =========================================================
# INVALID / NEEDS CLARIFICATION
# =========================================================

INVALID_QUERIES = [
    "book movie ticket",
    "weather today",
    "order pizza",
    "book cab",
    "train ticket booking",
    "mobile recharge",
    "buy laptop",
    "school admission",
    "flight booking",
    "cricket score",
    "bitcoin price",
    "buy groceries",
    "hotel booking",
    "doctor appointment",
    "play music",
    "youtube open",
    "instagram login",
    "facebook account issue",
    "food delivery",
    "nearest cinema",
    "what is my bank balance",
    "send money to friend",
    "cancel my order",
    "i want job",
    "college fees payment",
    "where is my parcel",
    "my phone screen broke",
    "bike petrol khatam",
    "mujhe movie dekhni hai",
    "kal ka mausam batao",
    "pizza mangwana hai",
    "cab book karo",
    "train ticket chahiye",
    "mobile recharge kar do",
    "doctor ka appointment chahiye",
    "song play karo",
    "facebook password reset",
    "cricket score kya hai",
    "బిర్యానీ ఆర్డర్ చేయాలి",
    "వాతావరణం ఎలా ఉంది",
    "సినిమా టికెట్ బుక్ చేయండి",
    "క్యాబ్ బుక్ చేయాలి",
    "డాక్టర్ అపాయింట్‌మెంట్ కావాలి",
    "క్రికెట్ స్కోర్ చెప్పు",
    "ఫోన్ రీచార్జ్ చేయాలి",
    "పాట ప్లే చేయండి",
    "asdfghjkl",
    "qwertyuiop",
    "zzzzzzzzzzzz",
    "1234567890",
    "@@@@@",
    "!!!!",
    "........",
    "hello",
    "help",
    "ok",
    "yes",
    "no",
    "hmmmm",
    "blah blah",
    "random words nothing",
    "i dont know",
    "just checking",
    "test input",
    "service please",
    "come fast",
    "very urgent",
    "need help",
    "mera kaam kar do",
    "kuch problem hai",
    "అర్జెంట్ సహాయం కావాలి",
    "ఏదో సమస్య ఉంది",
    "?? service ??",
    "123 abc xyz",
    "lol nothing",
    "who are you",
    "tell me joke",
    "write essay",
    "open settings",
    "download app",
    "call my friend",
]


EXTRA_SERVICE_ROLE_QUERIES = {
    "Electrical": [
        "My cooler is not working",
        "cooler fan stopped send electrician",
        "bijli worker needed for cooler",
        "पंखा काम नहीं कर रहा",
        "बिजली का स्विच जल गया",
        "इलेक्ट्रीशियन चाहिए अभी",
        "current nahi aa raha room me",
        "cooler motor not running",
    ],
    "Plumbing": [
        "tap ka pani ruk nahi raha",
        "bathroom flooding please send plumber",
        "नल से पानी लीक हो रहा है",
        "पाइप फट गया है",
        "फ्लश काम नहीं कर रहा",
        "sink water coming back fast",
        "pipe leakng under basin",
        "need plumber water tank overflow",
    ],
    "AC Repair": [
        "एसी ठंडा नहीं कर रहा",
        "एसी सर्विस चाहिए",
        "air conditioner throwing hot air",
        "ac compressor sound aa raha",
        "split ac ice ban raha",
        "ac remot not wrking",
        "ac gas refill krna hai",
        "bedroom ac suddenly off",
    ],
    "Carpenter": [
        "दरवाजा बंद नहीं हो रहा",
        "लकड़ी की अलमारी टूट गई",
        "curtain rod gir gaya fit karna",
        "plywood shelf banana hai",
        "table ka pair loose hai",
        "cupboard hinge tut gaya",
        "need carpenter for wall shelf",
        "chair leg brkn pls fix",
    ],
    "Cleaning": [
        "घर की सफाई चाहिए",
        "किचन बहुत गंदा है",
        "bathroom ganda hai deep clean",
        "water tank cleaning at home",
        "sofa stain remove karna",
        "floor sticky hai cleaner bhejo",
        "room sanitize after illness",
        "ghar saaf karna urgent",
    ],
    "Painting": [
        "दीवार का पेंट उतर रहा है",
        "पेंटर चाहिए घर के लिए",
        "paint smell old wall dirty",
        "door polish and paint required",
        "whitewash before moving",
        "wall putty crack fix paint",
        "paint patches after leakage repair",
        "room color change karna hai",
    ],
    "Gardening": [
        "बगीचा साफ करना है",
        "माली चाहिए पौधे सूख रहे हैं",
        "grass cutting in lawn",
        "water plants while i travel",
        "tree branches window touch kar rahe",
        "remove weeds from yard",
        "balcony planters install karna",
        "bagicha saaf karna hai",
    ],
    "Massage": [
        "मालिश चाहिए पीठ दर्द है",
        "मसाज therapist bhejo",
        "foot masaj needed today",
        "back is hurting badly",
        "neck stiff after office",
        "body pain massage chahiye",
        "leg cramps massage needed",
        "head massage migraine feeling",
    ],
}

for intent, queries in EXTRA_SERVICE_ROLE_QUERIES.items():
    SERVICE_ROLE_QUERIES[intent].extend(queries)


INVALID_QUERIES.extend([
    "no",
    "yes",
    "ok",
    "facebook account issue",
    "need help",
    "service please",
    "123 abc xyz",
    "this is not a service request",
    "tell me about your app",
    "my phone battery died",
    "what time is it",
    "I want to complain about noise",
    "please send my resume",
])


INTENT_NORMALIZER = {
    "Electrical": "electrical",
    "Plumbing": "plumbing",
    "AC Repair": "ac_repair",
    "Carpenter": "carpenter",
    "Cleaning": "cleaning",
    "Painting": "painting",
    "Gardening": "gardener",
    "Massage": "massage",
}

TEST_QUERIES = [
    (query, INTENT_NORMALIZER.get(intent, intent))
    for intent, queries in SERVICE_ROLE_QUERIES.items()
    for query in queries
] + [
    (query, "unknown")
    for query in INVALID_QUERIES
]


assert sum(len(queries) for queries in SERVICE_ROLE_QUERIES.values()) >= 500
assert len(TEST_QUERIES) >= 580
